model_settings:
  model_interpolation: 10
graph_settings:
  inflation: 0.05
  step: 0.5
  dim_x: 8
  dim_y: 8
search_settings:
  diagnols: True
vision_settings: 
  tag_size: 0.03
  lens_size: 2571.4
  camera_x_center: 320 
  camera_y_center: 240
transform_settings: 
  z_coefficent: 4
  x_coefficent: 1
vizualization_settings:
  map_name: "map.png"
robot_settings:
  velocity: 0.5