model_settings:
  model_interpolation: 10
  ego_agent_dim_x: 0.4
  ego_agent_dim_y: 0.6
  obstacle_dim_x: 0.4
  obstacle_dim_y: 0.1
graph_settings:
  inflation: 0.05
  step: 0.25
  dim_x: 8
  dim_y: 8
search_settings:
  diagnols: True
vision_settings: 
  tag_size: 0.03
  lens_size: 2571.4
  camera_x_center: 320 
  camera_y_center: 240
transform_settings: 
  z_coefficent: 4
  x_coefficent: 1
vizualization_settings:
  map_name: "map.png"
  plot_dim_x: 4
  plot_dim_y: 4
  show_plot: False
robot_settings:
  velocity: 0.5